/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thedotbot_ai_DotsSolver */

#ifndef _Included_com_thedotbot_ai_DotsSolver
#define _Included_com_thedotbot_ai_DotsSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thedotbot_ai_DotsSolver
 * Method:    chooseMove
 * Signature: ([[Lcom/thedotbot/screens/DotColor;IZZZ)Lcom/thedotbot/ai/Move;
 */
JNIEXPORT jobject JNICALL Java_com_thedotbot_ai_DotsSolver_chooseMove
  (JNIEnv *, jclass, jobjectArray, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_thedotbot_ai_DotsSolver
 * Method:    scoreAbove
 * Signature: (III)D
 */
JNIEXPORT jdouble JNICALL Java_com_thedotbot_ai_DotsSolver_scoreAbove
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
