/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thedotbot_screens_ScreenReader */

#ifndef _Included_com_thedotbot_screens_ScreenReader
#define _Included_com_thedotbot_screens_ScreenReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thedotbot_screens_ScreenReader
 * Method:    readScreen
 * Signature: (Ljava/io/File;)Lcom/thedotbot/screens/ScreenInfo;
 */
JNIEXPORT jobject JNICALL Java_com_thedotbot_screens_ScreenReader_readScreen
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
